name: Modelo de contenidos
on: [push,workflow_dispatch]

jobs:
  devdoc:
    runs-on: ubuntu-latest
    name: Generate model documentation
    steps:
      - name: Set environment variables
        run: | 
            TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
            echo "TRIGGERING_SHA_7=${TRIGGERING_SHA::7}" >> $GITHUB_ENV
            echo "TRIGGERING_SHA: $TRIGGERING_SHA"
            echo "COMPILATION_DATE=$(date +'%d %b %Y')" >> $GITHUB_ENV
            echo "GHTOKEN=${{ secrets.ACCIONTOKEN }}" >> $GITHUB_ENV
      - name: Actions/checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Checkout jarchi-hwo
        uses: actions/checkout@v4
        with:
            repository: hwong23/jarchi-hwo
            ref: main
            path: jarchi-hwo

      # - name: Checkout devocs-contd
      #   uses: actions/checkout@v4
      #   with:
      #     repository: hwong23/devocs-contd
      #     ref: ${{github.ref}}
      #     path: $HOME/devocs-contd
    
      # - name: Run model documentation
      #   id: devdoc
      #   uses: hwong23/git_hwo-action@v2.3
      #   with:
      #       archi-args: 'archiapp -m ./ --pluginDir ./plugins --script /tmp/jarchi-hwo/scr/list_concepts.ajs'

      - name: Gestiona contenidos
        run: |
          cd jarchi-hwo/scr/sh
          bash cpushcontd.sh . ${GITHUB_WORKSPACE} ${GITHUB_REF_NAME}

      - name: MV jarchi-hwo
        run: |
          mv ${{github.WORKSPACE}}/jarchi-hwo /tmp/jarchi-hwo
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.devdoc.outputs.time }}"
      - name: Add-and-commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'MD output'
