on: [push, workflow_dispatch]
permissions:
  contents: write
  
jobs:
  devdoc:
    runs-on: ubuntu-latest
    name: Generate model documentation
    steps:
      - name: Set environment variables
        run: | 
            TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
            echo "TMP_PATH=$HOME" >> $GITHUB_ENV
            echo "TRIGGERING_SHA_7=${TRIGGERING_SHA::7}" >> $GITHUB_ENV
            echo "TRIGGERING_SHA: $TRIGGERING_SHA"
            echo "COMPILATION_DATE=$(date +'%d %b %Y')" >> $GITHUB_ENV
      - name: Actions/checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Checkout jarchi-hwo
        uses: actions/checkout@v4
        with:
            repository: hwong23/jarchi-hwo
            ref: main
            path: jarchi-hwo
      - name: Checkout devocscontd
        uses: actions/checkout@v4
        with:
            repository: hwong23/devocs-contd
            ref: ${{github.ref}}
            path: devocs-contd
      # - name: Mv devocscontd
      #   run: |
      #     cp -R ${{github.WORKSPACE}}/devocs-contd ~/devocs-contd
      #     ls ~/devocs-contd
      - name: Run model documentation
        id: devdoc
        uses: hwong23/git_hwo-action@v2.1
        with:
          archi-args: 'archiapp -m ./ --pluginDir ./plugins --script ./jarchi-hwo/scr/list_concepts.ajs --alias bmmpropuesta'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.devdoc.outputs.time }}"
      - name: Add-and-commit
        run: |
          cd ${{github.WORKSPACE}}/devocs-contd
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m updated
          git push
        # uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        # with:
        #   cwd: ./devocs-contd
        #   message: 'MD output'
        #   # github_token: ${{ secrets.GITHUB_TOKEN }}
