on: [push,workflow_dispatch]

jobs:
  devdoc:
    runs-on: ubuntu-latest
    name: Generate model documentation
    steps:
      - name: Set environment variables
        run: | 
            TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
            echo "TRIGGERING_SHA_7=${TRIGGERING_SHA::7}" >> $GITHUB_ENV
            echo "TRIGGERING_SHA: $TRIGGERING_SHA"
            echo "COMPILATION_DATE=$(date +'%d %b %Y')" >> $GITHUB_ENV
      - name: Actions/checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Checkout jarchi-hwo
        uses: actions/checkout@v4
        with:
            repository: hwong23/jarchi-hwo
            ref: main
            path: jarchi-hwo
      - name: MV jarchi-hwo
        run: |
          # mv ${{github.WORKSPACE}}/jarchi-hwo /home/runner/work/_temp/_github_home/jarchi-hwo
          ls -l /home/runner/work/_temp/_github_home
    
      # - name: Run model documentation
      #   id: devdoc
      #   uses: hwong23/git_hwo-action@v2.3
      #   with:
      #     archi-args: 'archiapp -m ./ --pluginDir ./plugins --script /tmp/jarchi-hwo/scr/list_concepts.ajs'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.devdoc.outputs.time }}"
      - name: add-and-commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: 'MD output'
