on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate model documentation
    steps:
      - name: Run model documentation
        id: devdoc
        uses: hwong23/git_hwo-action@v2.7.8
        with:
          archi-args: 'Harry the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.devdoc.outputs.time }}"
